### ISSUE TITLE
[BUG] The centos-7 docker image has disfunctional repos

### ISSUE THREAD

**Issue by bocekm** [EuroLinux/containers-rfc#10]
**Describe the bug**
The eurolinux centos-7 docker container points to the now disfunctional CentOS Linux 7 repos. Yesterday was the end of life of CentOS Linux 7 and with that the repos moved over to an archive called Vault https://vault.centos.org/centos/7/. Some projects still need the CentOS Linux 7 container even after its EOL.

**Image versoin**
https://hub.docker.com/layers/eurolinux/centos-7/centos-7-7.9.40/images/sha256-2c226b92e7b9d5f0026a240433f2416c9dc1c4c138cbc2c0431ec5703593fd0c?context=explore

**Containerfile**
```
FROM eurolinux/centos-7

RUN yum update -y

CMD ["bash"]
```
**To Reproduce**
1. podman build -t centos7-container .
1. See error:
```
STEP 2/3: RUN yum update -y
<snip>
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
<snip>
Cannot find a valid baseurl for repo: base/7/x86_64
Error: building at STEP "RUN yum update -y": while running runtime: exit status 1
```

**Expected behavior**
The CentOS Linux 7 repofiles point to the archive https://vault.centos.org/centos/7/.

**Additional context**
Similar:

- https://github.com/EuroLinux/cloud-images-rfc/issues/11
- https://github.com/EuroLinux/cloud-images-rfc/issues/4
- https://github.com/EuroLinux/cloud-images-rfc/issues/6

**Comment by AlexBaranowski** [comment]
@bocekm I will personally change it today/tomorrow for the following images:

- CentOS 7
- EuroLinux 7
- Scientific Linux 7
- Oracle Linux 7 (They are not changing repos if I recall correctly, it's smart).

Thank you for your report 👍🏻 !

**Comment by AlexBaranowski** [comment]
@bocekm 

We pushed the newest version for:

- CentOS 7
- EuroLinux 7
- Oracle Linux 7
- Scientific Linux 7

Oracle Linux does not require a switch to vault/obsolete repositories.

- CentOS 7 and EuroLinux use the vault repositories.
- Scientific Linux 7 uses obsolete repositories.

Thank you for your issue :octocat:! I'm closing it. If you encounter an error or bug, do not hesitate to create a new issue or comment here (I'm not sure if you can reopen it, TBH).
